### ISSUE TITLE
First "Mow Area" - Settings after Start Cassandra Service

### ISSUE THREAD

**Issue by duemchen** [EinEinfach/CaSSAndRA#115]
Version 0.99.2, 
auch schon bei 'turn-figure-tests'

Neustart Cassandra.
Map wird angezeigt. 
Mow Settings zeigt Mow Area = True
Taste "Mow all or selected area" betätigt
Fehler: Nur die Ränder werden berechnet.

Mow Settings aufrufen
Mow Area = False setzen
Mow Area = True setzen
Speichern
Taste "Mow all or selected area" betätigt
Alles OK: Area wird berechnet.

Das Flag Mow Area wird nach Neustart nur optisch angezeigt, aber nicht korrekt initialisiert.

**Comment by ShadedSelf** [comment]
Were those settings created with an older Cassandra version?
Where are you applying the settings, on the gear button in the main page or on the settings page?

**Comment by EinEinfach** [comment]
Can't confirm that. All works as it should be.
1 Test:
- Mow area true in settings
- Reboot
- In overview called temporarly mow settings -> Mow area true is shown and whole area is calculated
2 Test:
- Mow area false in settings
- Reboot
- In overview called temporarly mow settings -> Mow are false is shown and just edges are calculated

**Comment by duemchen** [comment]
I'd make settings on main page 
Yes, older settings, transferred to the new dir .cassandra.
I will test with setting page again.
I will test it then with initial setting files from your sources and give report. Thanks.
(if this is the reason, i hope, at least the maps will be compatible all time in future)

**Comment by ShadedSelf** [comment]
I chaged the old string based dropdowns to boolean based switches a while ago.
 Seems like the switches are fine interpreting strings as booleans but Cassandra logic is not?

Should be fixed by reapplying settings or by manually removing the quotes from any boolean setting in the settings files.

Should we keep this issue open in case there is anyone else out there with old files?

**Comment by duemchen** [comment]
I have tested it. It is, like ShadedSelf say.

OLD
 "mowarea": "yes",
    "mowborder": 2,
    "mowexclusion": "yes",
    "mowborderccw": "yes"

change to this and all is ok:

NEW
"mowarea": true,
"mowborder": 2,
"mowexclusion": true,
"mowborderccw": true

If I save under Page Settings, the Format is updated to the new. But the Error remains. 
You must restart the service. Then all is ok.

Simple, but tricky and avoidable. In the future, such "structural" changes should be better checked and corrected automatically when the service is started. (I don't want to imagine maps are affected!) 
Thank you for your support!
